"""Structured output DTO for LLM query parsing (SYSTEM_DESIGN §12, SEARCH_SPEC §12)."""

from datetime import datetime, timedelta
from typing import Literal
from zoneinfo import ZoneInfo

from pydantic import BaseModel, Field
from rapidfuzz.distance import DamerauLevenshtein

from app.features.pipeline.domain.stages import Stage, Status
from app.features.search.engine.ast import (
    Added,
    Clause,
    CurrentStage,
    MovedTo,
    QueryAST,
    Reached,
    StatusIs,
    TimeInStage,
)
from app.features.search.engine.validator import validate_ast
from app.features.search.llm.interpreter import LLMOutcome
from app.features.search.parser.normalize import normalize_query
from app.features.search.parser.time_phrases import parse_time_phrase


class LLMClause(BaseModel):
    """Flat DTO for individual query clauses generated by LLM."""

    kind: Literal["current_stage", "status", "time_in_stage", "moved_to", "reached", "added"]
    stages: list[Stage] | None = None
    stage: Stage | None = None
    at_stage: Stage | None = None
    target: Stage | None = None
    status: Status | None = None
    negate: bool = False
    op: Literal["gt", "gte", "lt", "lte"] | None = None
    days: float | None = None
    since: str | None = None
    until: str | None = None


class LLMQuery(BaseModel):
    """Flat DTO for structured query representation from LLM."""

    clauses: list[LLMClause] = Field(default_factory=list)
    name_terms: list[str] = Field(default_factory=list)
    unsupported: bool = False

    def to_ast(
        self,
        q: str,
        now: datetime,
        tz: ZoneInfo,
    ) -> tuple[QueryAST | None, LLMOutcome]:
        """Convert DTO to strict QueryAST after grounding, date, and validation guards."""
        if self.unsupported:
            return None, "unsupported"

        if len(q) > 200:
            return None, "invalid"

        # 1. Grounding check (§12): Every name_term must appear in q (equality or <= 1 edit)
        q_norm = normalize_query(q)
        q_tokens = [t.lower() for t in q_norm.split()]

        for name in self.name_terms:
            name_clean = name.lower().strip()
            if not name_clean:
                continue

            grounded = False
            for tok in q_tokens:
                if tok == name_clean:
                    grounded = True
                    break
                dist = int(DamerauLevenshtein.distance(tok, name_clean))
                if dist <= 1:
                    grounded = True
                    break

            if not grounded:
                return None, "ungrounded"

        # 2. Date guard and clause mapping
        ast_clauses: list[Clause] = []
        min_allowed_date = now - timedelta(days=730)  # 2 years past

        for c in self.clauses:
            since_dt: datetime | None = None
            until_dt: datetime | None = None

            if c.since:
                try:
                    since_dt, parsed_until = parse_time_phrase(c.since, now, tz)
                    if parsed_until and not c.until:
                        until_dt = parsed_until
                except ValueError:
                    try:
                        since_dt = datetime.fromisoformat(c.since.replace("Z", "+00:00"))
                    except ValueError:
                        return None, "invalid"

            if c.until:
                try:
                    _, until_dt = parse_time_phrase(c.until, now, tz)
                except ValueError:
                    try:
                        until_dt = datetime.fromisoformat(c.until.replace("Z", "+00:00"))
                    except ValueError:
                        return None, "invalid"

            # Date guard check
            for dt in (since_dt, until_dt):
                if dt is not None:
                    if dt > now:
                        return None, "invalid"
                    if dt < min_allowed_date:
                        return None, "invalid"

            if c.kind == "current_stage":
                stages_list = c.stages or ([c.stage] if c.stage else [])
                if not stages_list:
                    return None, "invalid"
                ast_clauses.append(CurrentStage(stages=stages_list))

            elif c.kind == "status":
                if c.status is None:
                    return None, "invalid"
                ast_clauses.append(StatusIs(status=c.status, negate=c.negate, at_stage=c.at_stage))

            elif c.kind == "time_in_stage":
                days_val = c.days if c.days is not None else 7.0
                if days_val <= 0:
                    return None, "invalid"
                ast_clauses.append(TimeInStage(stage=c.stage, op=c.op or "gt", days=days_val))

            elif c.kind == "moved_to":
                target_stage = c.target or c.stage
                if target_stage is None:
                    return None, "invalid"
                ast_clauses.append(MovedTo(target=target_stage, since=since_dt, until=until_dt))

            elif c.kind == "reached":
                if c.stage is None:
                    return None, "invalid"
                ast_clauses.append(Reached(stage=c.stage, negate=c.negate))

            elif c.kind == "added":
                ast_clauses.append(Added(since=since_dt, until=until_dt))

        ast = QueryAST(
            clauses=ast_clauses,
            name_terms=[n.lower().strip() for n in self.name_terms if n.strip()],
            source="llm",
        )

        # 3. Validator check
        val_errors = validate_ast(ast, now)
        if val_errors:
            return None, "invalid"

        return ast, "ok"
